apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivolve-deploy
  namespace: ivolve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ivolve
  template:
    metadata:
      labels:
        app: ivolve
    spec:
      containers:
      - name: ivolve-app
        image: mohamedmotaz350/finalapplication:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
